apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-service"
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort | default .Values.app.env.PORT }}
      nodePort: {{ .Values.app.service.nodePort }}
  type: NodePort