global:
  namespace: find-fuel
  environment: dev

app:
  name: find-fuel-app
  deployment:
    replicaCount: 1
    image: find-fuel-app
  service:
    port: 80
    nodePort: 30090
  env:
    HOST: ""
    PORT: 9090
    DB_DRIVER: postgres
    DB_HOST: host.docker.internal
    DB_PORT: 5432
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_NAME: postgres
    DB_SSLMODE: disable
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  livenessProbe:
    httpGet:
      path: /health
      port: 
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health
      port: 
    initialDelaySeconds: 5
    periodSeconds: 5

migrations:
  name: find-fuel-migrations
  job:
    image: find-fuel-migrations
    backoffLimit: 3

updateData:
  name: find-fuel-update-data
  cronJob: 
    schedule: "* * * * *"
    image: find-fuel-update-data