apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appEnvConfigMap.name }}
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $key, $value := .Values.appEnvConfigMap.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}