apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dbConfigMap.name }}
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $key, $value := .Values.dbConfigMap.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}